data-processing:
	./csv2libsvm.pl ../data/train.csv ../data/train_cont.libsvm ../data/train_disc.libsvm
	./csv2libsvm.pl ../data/test.csv ../data/test_cont.libsvm ../data/test_disc.libsvm
	
clean-data:
	rm ../data/*

clean-out:
	rm -rf ../out/* 
